yaml:
    name: theFactory-backend
    aliases:
        - properties.yml
        - env.yml

server:
    port: ${APP_PORT:8080}
    servlet:
        context-path: ${APP_CONTEXT_PATH:/api}
    compression:
        enabled: true
        min-response-size: 1024
    forward-headers-strategy: native

spring:
    application:
        name: theFactory-backend
    banner:
        location: classpath:banner.txt
    profiles:
        active: ${PROFILE:dev}
    datasource:
        url: jdbc:postgresql://localhost:5432/factory
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:5}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        user:
            name: admin
            password: password

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /v3
